# Generated by Django 5.1.3 on 2024-12-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
