# Generated by Django 5.1.3 on 2024-12-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_amount_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_total',
            field=models.CharField(max_length=10),
        ),
    ]
